### ISSUE TITLE
exception on 6.2 using development

### ISSUE THREAD

**Issue by davdenic** [FluidTYPO3/fluidbackend#18]
Hi, i'm try to using the development branch on a 6.2 but i get an exception when in BE i create a new Fluid Backend Engine -> Module configuration 
I use the latest flux development branch (7.2.0).
Thanks

Uncaught TYPO3 Exception
#1: PHP Warning: Illegal string offset 'templateRootPath' in /var/www/typo3/typo3conf/ext/fluidbackend/Classes/Provider/Configuration/StorageConfigurationProvider.php line 102 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/var/www/TYPO3_CMS_6_2/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101.

**Comment by NamelessCoder** [comment]
Fixed; but fluidbackend still lacks a documentation update. The API of Outlets and Pipes have been moved to Flux itself and a ViewHelper interface for that API is being made. However: it will no longer throw Exceptions ;)
