### ISSUE TITLE
[BUG] Empty Variable $GLOBALS['TBE_MODULES']['_dispatcher']

### ISSUE THREAD

**Issue by Madii** [FluidTYPO3/fluidbackend#19]
Hey Claus and others,

well don't know if it's the reason of Typo3 7.1 but after activating fluidbackend i get this error in the FE:

`#1: PHP Warning: array_unshift() expects parameter 1 to be array, null given in /var/www/typo3conf/ext/fluidbackend/ext_tables.php line 8`
->
 
`7 TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "array_unshift() expects parameter 1 to be array, null given", "/var/www/typo3conf/ext/fluidbackend/ext_tables.php", 8, array)

6 array_unshift(NULL, "FluidTYPO3\Fluidbackend\Override\Backend\Module\ModuleRunner")`

Maybe it's also the reason that i've tried the `site` Extension. ;-)

**Comment by jmverges** [comment]
Hi @Madii,

I can confirm the same issue.

**Comment by akosf** [comment]
Hello, the same problem seems to have returned in typo3 7.6.

**Comment by mrmoree** [comment]
same problem here
