### ISSUE TITLE
Error in the first launch of Typo3 7.4.0

### ISSUE THREAD

**Issue by konstantin83** [FluidTYPO3/fluidbackend#24]
Upgraded from typo3 6.2.14 to 7.4.0.
Made all uprgade stuff in install tool, but got a error trying to get to backend:
Fatal error: Class 'FluidTYPO3\Fluidbackend\Override\Backend\Module\ModuleLoader' not found in /home/k/konstantin/typo3_src-7.4.0/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4343

How to fix this?

**Comment by NamelessCoder** [comment]
Hi Konstantin,

A patch is coming for this one (already committed to development branch). To fix this quickly you can pull the development branch - or you can temporarily uninstall fluidbackend. It should not be long (days) until we can create a new TER release.

**Comment by konstantin83** [comment]
Ok, thanks for response. How can i download development branch?

**Comment by NamelessCoder** [comment]
You'll either need the "git" command line utility or a GUI for it and then `git clone https://github.com/FluidTYPO3/fluidbackend.git` - or you can get a ZIP archive that you can upload or extract as you please, from https://github.com/FluidTYPO3/fluidbackend/archive/development.zip

**Comment by konstantin83** [comment]
It didn't help... white screen after entering login and password to BE.

**Comment by NamelessCoder** [comment]
Make sure you clear the caches (via the install tool). Unfortunately TYPO3 caches reflections of classes and stores absolute references to files - manually updating an extension in which class files have changed can sometimes cause errors.

Log into your install tool and find the "Important actions" item, then use the "clear all caches" function there. The way it is implemented in the install tool lets you clear caches even if they contain this incorrect data. In some rare cases you may also need to use the "Cleanup" item in install tool to remove temporary files. Usually though, clearing all caches is enough.

On a related note, I released fluidbackend 1.0.1 just today so you should be able to get it from TER in a while.

PS: the reason you see a white screen is that PHP errors are disabled, either in TYPO3 or in your php.ini. To enable it in TYPO3 you can set the "Development" context also in the install tool. Fixing it in ini.php of course depends on your system and which "flavor" of PHP you use.

Hope this helps!

**Comment by konstantin83** [comment]
Thank you very much for your attention!
