### ISSUE TITLE
Empty Compressed CSS file in iframe with f:be.container

### ISSUE THREAD

**Issue by kimamil** [FluidTYPO3/fluidbackend#25]
I am not sure why this is not going. But in my TYPO3 6.2 Backend module, I want to include the bootstrap.min.css from maxcdn. After reading through the doc I decided to go with f:be:container and use the includeCssFiles argument to load it as follows:

    <f:be.container loadJQuery="true" includeCssFiles="{0: '{f:uri.external(uri:\'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\')}'}">

I also get a compressed css file in the iframe, but it is empty:

    <link media="all" href="../typo3temp/compressor/bootstrap.min-cfc9fc44495c6d385418e5ee4d0ab2cd.css?1447181637" type="text/css" rel="stylesheet">

**Comment by NamelessCoder** [comment]
`f:be.container` belongs to the Fluid package which is not under our control and is handed off to the PageRenderer which is also not under our control - please report this to the [TYPO3 core bug tracker](https://forge.typo3.org/projects/typo3cms-core/issues).
